In [1]:
#pandas 임포트
import pandas as pd

#csv 파일 읽어와서 f에 바인딩
f = pd.read_csv("/content/wine.csv")

#첫번째 행의 모든 열을 가져오기
print(f.iloc[0,:])

fixed acidity            7.4000
volatile acidity         0.7000
citric acid              0.0000
residual sugar           1.9000
chlorides                0.0760
free sulfur dioxide     11.0000
total sulfur dioxide    34.0000
density                  0.9978
pH                       3.5100
sulphates                0.5600
alcohol                  9.4000
quality                  5.0000
class                    1.0000
Name: 0, dtype: float64


In [ ]:
#f변수의 correlation을 계산하여 반환
f.corr()

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000          0.219008     0.324436   
volatile acidity           0.219008          1.000000    -0.377981   
citric acid                0.324436         -0.377981     1.000000   
residual sugar            -0.111981         -0.196011     0.142451   
chlorides                  0.298195          0.377124     0.038998   
free sulfur dioxide       -0.282735         -0.352557     0.133126   
total sulfur dioxide      -0.329054         -0.414476     0.195242   
density                    0.458910          0.271296     0.096154   
pH                        -0.252700          0.261454    -0.329808   
sulphates                  0.299568          0.225984     0.056197   
alcohol                   -0.095452         -0.037640    -0.010493   
quality                   -0.076743         -0.265699     0.085532   
class                      0.486740          0.653036    -0.187397   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity              -0.111981   0.298195            -0.282735   
volatile acidity           -0.196011   0.377124            -0.352557   
citric acid                 0.142451   0.038998             0.133126   
residual sugar              1.000000  -0.128940             0.402871   
chlorides                  -0.128940   1.000000            -0.195045   
free sulfur dioxide         0.402871  -0.195045             1.000000   
total sulfur dioxide        0.495482  -0.279630             0.720934   
density                     0.552517   0.362615             0.025717   
pH                         -0.267320   0.044708            -0.145854   
sulphates                  -0.185927   0.395593            -0.188457   
alcohol                    -0.359415  -0.256916            -0.179838   
quality                    -0.036980  -0.200666             0.055463   
class                      -0.348821   0.512678            -0.471644   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                    -0.329054  0.458910 -0.252700   0.299568   
volatile acidity                 -0.414476  0.271296  0.261454   0.225984   
citric acid                       0.195242  0.096154 -0.329808   0.056197   
residual sugar                    0.495482  0.552517 -0.267320  -0.185927   
chlorides                        -0.279630  0.362615  0.044708   0.395593   
free sulfur dioxide               0.720934  0.025717 -0.145854  -0.188457   
total sulfur dioxide              1.000000  0.032395 -0.238413  -0.275727   
density                           0.032395  1.000000  0.011686   0.259478   
pH                               -0.238413  0.011686  1.000000   0.192123   
sulphates                        -0.275727  0.259478  0.192123   1.000000   
alcohol                          -0.265740 -0.686745  0.121248  -0.003029   
quality                          -0.041385 -0.305858  0.019506   0.038485   
class                            -0.700357  0.390645  0.329129   0.487218   

                       alcohol   quality     class  
fixed acidity        -0.095452 -0.076743  0.486740  
volatile acidity     -0.037640 -0.265699  0.653036  
citric acid          -0.010493  0.085532 -0.187397  
residual sugar       -0.359415 -0.036980 -0.348821  
chlorides            -0.256916 -0.200666  0.512678  
free sulfur dioxide  -0.179838  0.055463 -0.471644  
total sulfur dioxide -0.265740 -0.041385 -0.700357  
density              -0.686745 -0.305858  0.390645  
pH                    0.121248  0.019506  0.329129  
sulphates            -0.003029  0.038485  0.487218  
alcohol               1.000000  0.444319 -0.032970  
quality               0.444319  1.000000 -0.119323  
class                -0.032970 -0.119323  1.000000

In [3]:
#X에 7가지 데이터 바인딩
X = f[['volatile acidity','residual sugar','chlorides','total sulfur dioxide','density','quality','class']]
#데이터 프레임 'f'에서 alcohol열만을 선택하여 y변수에 바인딩
y = f['alcohol']

#X 데이터프레임에서 첫 4000개의 행과 모든 열을 선택하여 X_train변수에 저장
X_train = X.iloc[:4000,:]
#X 데이터프레임에서 4000번째 행부터 마지막 행까지와 모든 열을 선택하여 X_valid에 저장
X_valid = X.iloc[4000:,:]
#이하동문
y_train = y.iloc[:4000]
y_valid = y.iloc[4000:]

In [ ]:
print(len(X_train))
print(len(X_valid))
print(len(y_train))
print(len(y_valid))

4000
2497
4000
2497


In [4]:
#다항 회귀 모델에 필요한 특성을 생성한는 작업
from sklearn.preprocessing import PolynomialFeatures

#degree파라미터는 생성할 다항식의 최고 차수를 지정하며, ->2차 다항식 생성
#include_bias파라미터는 절편(intercept)을 생성할지 여부를 지정 -> 절편 생성 x
poly_features = PolynomialFeatures(degree=2, include_bias=False)

#X_train데이터를 이용하여 다항식 특성을 생성하고,
#이를 학습시키기 위한 파라미터 계산
poly_features.fit(X_train)

#transform메소드를 호출하여 X_train데이터를 변환
#poly_X는 다항식 특성이 추가도니 새로운 데이터 셋
poly_X= poly_features.transform(X_train)

'''
위코드는 PolynomialFeatures 객체를 이용하여 다항 회귀 모델에 필요한 다항식 특성을 생성하고,
이를 훈련용 데이터셋 X_train에 추가하여 새로운 데이터셋 poly_X를 생성하는 작업을 수행
이렇게 생성된 poly_X는 기존의 X_train데이터에 비해 다양한 다항식 특성을 추가함으로써
모델의 학습과 예측 성능을 향상시킬 수 있음
'''

'\n위코드는 PolynomialFeatures 객체를 이용하여 다항 회귀 모델에 필요한 다항식 특성을 생성하고,\n이를 훈련용 데이터셋 X_train에 추가하여 새로운 데이터셋 poly_X를 생성하는 작업을 수행\n이렇게 생성된 poly_X는 기존의 X_train데이터에 비해 다양한 다항식 특성을 추가함으로써\n모델의 학습과 예측 성능을 향상시킬 수 있음\n'

In [5]:
#sklearn라이브러리의 SGDRegressor클래스를 사용하여, 다항 회귀 모델을 학습
from sklearn.linear_model import SGDRegressor
'''
SGDRegressor클래스의 sgd_reg인스턴스 생성
max_iter(반복횟수), tol(종료기준), penalty(정규화 항),
eta0(학습률), random_state(랜덤 시드)설정
'''
sgd_reg = SGDRegressor(max_iter=50, tol=1e-3, penalty=None, eta0=0.1, random_state=42)

#fit 메서드를 홀출하여 다항 회귀 모델을 학습
#이 때, 입력변수(poly_X)를 사용하고, 타겟변수(y_train)를 사용
sgd_reg.fit(poly_X, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_stochastic_gradient.py:1548: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor(eta0=0.1, max_iter=50, penalty=None, random_state=42)

In [8]:

#import numpy as np

#poly_features객체를 사용하여 다항식 생성
#생성된 다항식 객체를 transform()메서드로 X_valid데이터를 다항식으로 변환
#변환된 X_new_poly를 사용하여 모델이 새로운 데이터에 대해 예측을 수행함
X_new_poly = poly_features.transform(X_valid)
print(X_new_poly)

[[1.6e-01 2.0e+00 4.4e-02 ... 1.6e+01 0.0e+00 0.0e+00]
 [2.6e-01 8.2e+00 3.8e-02 ... 3.6e+01 0.0e+00 0.0e+00]
 [3.3e-01 2.1e+00 3.4e-02 ... 3.6e+01 0.0e+00 0.0e+00]
 ...
 [2.4e-01 1.2e+00 4.1e-02 ... 3.6e+01 0.0e+00 0.0e+00]
 [2.9e-01 1.1e+00 2.2e-02 ... 4.9e+01 0.0e+00 0.0e+00]
 [2.1e-01 8.0e-01 2.0e-02 ... 3.6e+01 0.0e+00 0.0e+00]]


In [7]:
#모델의 성능을 평가하기 위해 평균 제곱 오차(MSE)를 계산하고 출력하는 코드
from sklearn.metrics import mean_squared_error

#sgd_reg를 사용하여 예측값 y_predict를 계산
y_predict = sgd_reg.predict(X_new_poly)

#mean_squared_error()함수는 예측값과 실제값 사이의 평균 제곱 오차를 계산함
#예측한 결과인 y_predict와 실제 결과인 y_valid를 사용
print(mean_squared_error(y_predict,y_valid))

#MSE가 낮을수록 모델의 예측이 실제 결과에 가까움

8.025251371673693e+35
